- name: " Upgrade all packages"
  yum:
    name: '*'
    state: latest

- name: "Instal Vim "
  yum:
    name: vim-enhanced
    state: latest


- name: "install git"
  yum:
    name: git
    state: latest
